server:
  port: 8081

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

  application:
    name: ai-service

  profiles:
    active: dev,private
  # Redis配置已移除，使用RAGFlow远程服务
  datasource:
    url: jdbc:mysql://localhost:3306/knowledge_base?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    dashscope:
      api-key: sk-a75e2109f45e4704b3c14cb25e245186
      chat:
        options:
          incremental-output: true
          model: qwen-max-latest
      embedding:
        options:
          model: text-embedding-v4
      image:
        options:
          model: wanx-v1
      read-timeout: 600000

  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
        ip: 127.0.0.1
      config:
        import-check:
          enabled: false


    sentinel:
      transport:
        dashboard: localhost:8080
      eager: true

    gateway:
      routes:
        - id: ai-service
          uri: lb://ai-service
          predicates:
            - Path=/ai/**
          filters:
            - StripPrefix=1

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true

# RAGFlow配置
ragflow:
  base-url: http://192.168.100.128:80
  api-key: ragflow-JlMTExYzk0NWQ1NzExZjBiNzI0MDI0Mm # 从环境变量获取API Key，如果没有则使用空字符串

# 知识库功能已完全迁移到RAGFlow远程服务

